### ISSUE TITLE
无法连接NTFS的移动硬盘

### ISSUE THREAD

**Issue by baibinghere** [xjtuecho/HIWIFI#2]
思来想去，还是开一个issue吧，虽然100%不可能得到作者回复啦。

环境：

![image](https://user-images.githubusercontent.com/9794472/204077996-9198a9d2-6d7a-440c-8e64-0397ec27b2b8.png)

系统日志如下：

```shell
Nov 26 15:02:37 kernel: usb 1-1: new high-speed USB device number 8 using ehci-platform
Nov 26 15:02:37 kernel: usb 1-1: New USB device found, idVendor=0bc2, idProduct=ab26
Nov 26 15:02:37 kernel: usb 1-1: Product: BUP Slim RD
Nov 26 15:02:37 kernel: usb 1-1: Manufacturer: Seagate
Nov 26 15:02:37 kernel: usb 1-1: SerialNumber: NA98DX2G
Nov 26 15:02:37 kernel: scsi6 : usb-storage 1-1:1.0
Nov 26 15:02:40 kernel: scsi 6:0:0:0: Direct-Access     Seagate  BUP Slim RD      0108 PQ: 0 ANSI: 6
Nov 26 15:02:40 kernel: sd 6:0:0:0: Attached scsi generic sg0 type 0
Nov 26 15:02:40 usb_modeswitch: no rule for device 0bc2:ab26
Nov 26 15:02:40 kernel: sd 6:0:0:0: [sda] 3907029167 512-byte logical blocks: (2.00 TB/1.81 TiB)
Nov 26 15:02:40 kernel: sd 6:0:0:0: [sda] Write Protect is off
Nov 26 15:02:40 kernel: sd 6:0:0:0: [sda] Mode Sense: 47 00 00 08
Nov 26 15:02:40 kernel: sd 6:0:0:0: [sda] Write cache: enabled, read cache: enabled, doesn't support DPO or FUA
Nov 26 15:02:40 kernel:  sda: sda1
Nov 26 15:02:40 kernel: sd 6:0:0:0: [sda] Attached SCSI disk
Nov 26 15:02:40 automount: /sbin/automount.sh sda1    AiDisk_a1
Nov 26 15:02:41 automount: mount  device /dev/sda1 (ntfs) to /media/Media @@@@@ /media/AiDisk_a1
Nov 26 15:02:41 kernel: ufsd: use builtin utf8 instead of kernel utf8
Nov 26 15:02:41 automount: Unable to mount device /dev/sda1 (ntfs) to /media/Media!
Nov 26 15:02:51 kernel: ufsd: use builtin utf8
```

SSH登录到系统中，手动执行结果如下：

```
HC5861:/opt # /sbin/automount.sh sda1    AiDisk_a1
mount: mounting /dev/sda1 on /media/Media failed: Invalid argument
HC5861:/opt # modprobe -l | grep ufsd
kernel/fs/ufsd/ufsd.ko
HC5861:/opt # modprobe -l | grep antfs
HC5861:/opt #
```

显然只能使用ufsd的方式mount，手动执行结果如下：

```shell
HC5861:/ # mount -t ufsd /dev/sda1  /opt -o noatime,sparse,nls=utf8,force
mount: mounting /dev/sda1 on /opt failed: Invalid argument
```

怀疑是ufsd.ko有问题？我也不知道从哪里能看到详细日志，所以只能作罢。

**Comment by xjtuecho** [comment]
众所周知，Linux对NTFS支持并不好，建议使用EXT4或者FAT32文件系统

**Comment by baibinghere** [comment]
@xjtuecho ，感谢回复！我只是报着试一试的态度想找找原因。

我在华硕的固件就能稳定运行NTFS，所以想研究研究，毕竟2TB的视频都存在这个NTFS磁盘中，倒腾一次确实麻烦。

**Comment by xjtuecho** [comment]
> 

帮忙看一下华硕固件用的是哪个NTFS驱动，padavan默认用的ufsd，而且我一直用的是EXT4，并没有测试NTFS

**Comment by baibinghere** [comment]
华硕的固件使用的是Tuxera NTFS driver，从它们[官网](https://www.asuswrt-merlin.net/about)上看到这么一句：

> enhanced NTFS performance (through the proprietary drivers used by Asus from either Paragon or Tuxera)

查了一下，我的梅林系统使用的是：

```shell
baib2@RT-AC86U-6B50:/tmp/mnt/sda1# modprobe -D tntfs
insmod /lib/modules/4.1.27/kernel/fs/tntfs.ko

root@VM-0-3-ubuntu:~# modinfo tntfs.ko
filename:       /root/tntfs.ko
alias:          fs-tntfs
license:        Commercial. For support email ntfs-support@tuxera.com.
version:        3018.6.22d
description:    Read/Write NTFS Driver
author:         Tuxera Inc. & Anton Altaparmakov
srcversion:     3D90974529DB5FBB45A7D38
depends:
vermagic:       4.1.27 SMP preempt mod_unload aarch64
```

都不是同一个产品了，的确不好比较。

**Comment by xjtuecho** [comment]
> 华硕的固件使用的是Tuxera NTFS driver，从它们[官网](https://www.asuswrt-merlin.net/about)上看到这么一句：
> 
> > enhanced NTFS performance (through the proprietary drivers used by Asus from either Paragon or Tuxera)
> 
> 查了一下，我的梅林系统使用的是：
> 
> ```shell
> baib2@RT-AC86U-6B50:/tmp/mnt/sda1# modprobe -D tntfs
> insmod /lib/modules/4.1.27/kernel/fs/tntfs.ko
> 
> root@VM-0-3-ubuntu:~# modinfo tntfs.ko
> filename:       /root/tntfs.ko
> alias:          fs-tntfs
> license:        Commercial. For support email ntfs-support@tuxera.com.
> version:        3018.6.22d
> description:    Read/Write NTFS Driver
> author:         Tuxera Inc. & Anton Altaparmakov
> srcversion:     3D90974529DB5FBB45A7D38
> depends:
> vermagic:       4.1.27 SMP preempt mod_unload aarch64
> ```
> 
> 都不是同一个产品了，的确不好比较。

pavavan使用的ntfs驱动是ufsd，此外还有ntfs-3g和antfs可选，具体我没有测试过，以后有时间我试一下。

**Comment by xjtuecho** [comment]
> 华硕的固件使用的是Tuxera NTFS driver，从它们[官网](https://www.asuswrt-merlin.net/about)上看到这么一句：
> 
> > enhanced NTFS performance (through the proprietary drivers used by Asus from either Paragon or Tuxera)
> 
> 查了一下，我的梅林系统使用的是：
> 
> ```shell
> baib2@RT-AC86U-6B50:/tmp/mnt/sda1# modprobe -D tntfs
> insmod /lib/modules/4.1.27/kernel/fs/tntfs.ko
> 
> root@VM-0-3-ubuntu:~# modinfo tntfs.ko
> filename:       /root/tntfs.ko
> alias:          fs-tntfs
> license:        Commercial. For support email ntfs-support@tuxera.com.
> version:        3018.6.22d
> description:    Read/Write NTFS Driver
> author:         Tuxera Inc. & Anton Altaparmakov
> srcversion:     3D90974529DB5FBB45A7D38
> depends:
> vermagic:       4.1.27 SMP preempt mod_unload aarch64
> ```
> 
> 都不是同一个产品了，的确不好比较。

我测试过，默认的usfd驱动是可以连接NTFS格式移动硬盘的，我试了ANTFS驱动，也没有问题。
如果设备是HC5661或者HC5761的话，由于路由器使用5V供电输入，USB输出电压会偏低，导致移动硬盘无法使用，这是一个常见的原因。

**Comment by baibinghere** [comment]
你用 `HC5861` 测试的吗？我是在`HC5861`上测试的，在命令行遇到的错误是这个：

```shell
HC5861:/opt # /sbin/automount.sh sda1    AiDisk_a1
mount: mounting /dev/sda1 on /media/Media failed: Invalid argument
```

我看到您刚刚发布了ANTFS驱动的固件，我空了也试试。谢谢！

**Comment by xjtuecho** [comment]
> 你用 `HC5861` 测试的吗？我是在`HC5861`上测试的，在命令行遇到的错误是这个：
> 
> ```shell
> HC5861:/opt # /sbin/automount.sh sda1    AiDisk_a1
> mount: mounting /dev/sda1 on /media/Media failed: Invalid argument
> ```
> 
> 我看到您刚刚发布了ANTFS驱动的固件，我空了也试试。谢谢！

测试用的HC5861，实测NTFS一切正常。

**Comment by selfcan** [comment]
大佬，能否分享一下5861的配置文件，想自行编译一下固件，谢谢！
