### ISSUE TITLE
HC5761 5G WIFI无法中继

### ISSUE THREAD

**Issue by hanfengcan** [xjtuecho/HIWIFI#6]
使用[v221201](https://github.com/xjtuecho/HIWIFI/tree/master/Padavan/v221201)的固件，连接到小米4C的2.4GWiFi可以正常中继。

连接到Redmi AX3000的5G WiFi中继就无法正常连接。 

另外 4C的SSID是英文， Redmi AX3000的SSID是中文，不知是否有影像

**Comment by xjtuecho** [comment]
抱歉，该固件并没有在小米设备上测试
